### ISSUE TITLE
Intermittent deploy failure: TypeError: self.intercepts.console[type].apply is not a function

### ISSUE THREAD

**Issue by hypexr** [serverless-components/graphql#22]
Hello, we've seen some intermittent deployment failures when deploying graphql components.  I put this in with support and they asked me to put it in here.

Here's the output:

```Executing: AWS_PROFILE=rio-beta sls deploy --stage dev --debug in apiBase
25lInitializing...
Action: "deploy" - Stage: "dev" - Org: "rioverde" - App: "api" - Name: "base"
Deploying...
Deploying "api-v8-dev-nw3gq5z" to the "us-west-2" region.
TypeError: self.intercepts.console[type].apply is not a function
at intercept (/opt/nodejs/node_modules/@serverless/core/node_modules/@serverless/platform-client/src/index.js:1289:41)
at console.log (/opt/nodejs/node_modules/@serverless/core/node_modules/@serverless/platform-client/src/index.js:1298:7)
at log (/var/task/serverless.js:28:30)
at GraphQL.deploy (/var/task/serverless.js:95:5)
at async Runtime.module.exports [as handler] (/opt/nodejs/node_modules/@serverless/core/handler.js:337:24)
6s › Serverless › self.intercepts.console[type].apply is not a function
Documentation: https://github.com/serverless/components
Support: https://app.serverless.com/support
Slack: https://www.serverless.com/slack/
25hError executing "AWS_PROFILE=rio-beta sls deploy --stage dev --debug" Exit code: 1
Error: Process completed with exit code 1```

**Comment by eahefnawy** [comment]
@hypexr could you try running without the `--debug` flag?

Also, if possible, could you share code snippets of your logging logic in your application? I think it's something with the logs.

**Comment by hypexr** [comment]
Haven't been able to reproduce this recently.
