### ISSUE TITLE
ConcurrentModificationException error on deploy

### ISSUE THREAD

**Issue by babelian** [serverless-components/graphql#25]
I've inherited a codebase using this component, and am getting the error below when attempting to deploy. Obviously the error is remote, but I can't see why I would be having this issue deploying when the previous dev did not.

There's one issue here (https://github.com/serverless/serverless-graphql/issues/316) which mentions it happening intermittently, but I'm getting it for every attempt (unless I get a timeout which is also happening).

```
% nvm exec 14.15.4 sls deploy --debug --stage=dev  

Running node v14.15.4 (npm v6.14.10)
Initializing...
Action: "deploy" - Stage: "dev" - Org: "OrgName" - App: "appname-graphql" - Name: "appname-graphql"
Deploying...
Deploying "appname-graphql-n7lr7nr" to the "us-east-1" region.
Deploying Role "appname-graphql-n7lr7nr" to the "us-east-1" region.
Deploying resolvers for AppSync API with ID "yeaexzl3gjeqtak3fftwqu5btm".

 ConcurrentModificationException: Data source locked due to concurrent update, please retry
    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)

14s › Serverless › Data source locked due to concurrent update, please retry 

  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 
```

The only thing of note is that `n7lr7n` in `appname-graphql-n7lr7n` is different from the existing dev stage deployment, possibly because the OrgName has changed. If there's any hints on how to override this so I can get the original hash, that might indirectly solve the problem (in the hope its only happening when doing a fresh deploy). 

I tried modifying the `apiId:` which seems to work for resolvers line, but doesn't change the general naming.

**Comment by mwawrusch** [comment]
I reported this multiple times over the last year, the team at serverless never fixed that.

**Comment by wxxedu** [comment]
It doesn't seem to be fixed by now also.

**Comment by wxxedu** [comment]
Any means to fix this?
